## *Importing libraries*

In [1]:
import numpy as np
import pandas as pd

# **Part 1**
## **Exercise 1**
### 1. Creating Series

In [2]:
temperatures = pd.Series([20, 24, 19, 26, 25], name="temperatures")
temperatures

0    20
1    24
2    19
3    26
4    25
Name: temperatures, dtype: int64

#### 1.2 Displaying its max

In [3]:
print(temperatures.max())

26

#### 1.3 Displaying its min

In [4]:
print(temperatures.min())

19

#### 1.4 Displaying its mean

In [5]:
print(temperatures.mean())

22.8

### 2. Creating a df

In [6]:
products_df = pd.DataFrame({
    "name":     ["Phone",	"Laptop",	"Earbuds",	"Charger"],
    "price":    [120000,	150000,		4000,		3500],
    "quantity": [10,		5,			20,			18]
})
products_df

      name   price  quantity
0    Phone  120000        10
1   Laptop  150000         5
2  Earbuds    4000        20
3  Charger    3500        18

### 3. Working with product_df
#### 3.1 Displaying price column

In [7]:
products_df.price

0    120000
1    150000
2      4000
3      3500
Name: price, dtype: int64

#### 3.2 Displaying price type

In [8]:
type(products_df.price)

pandas.Series

# **Part 2**
## **Exercise 2**
### 1. Loading the dataset

In [9]:
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 2. Displaying the df
#### 2.1 First 5 rows

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### 2.1 Last 10 rows

In [11]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 3. Displaying 5 sample rows

In [12]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
756,757,0,3,"Carlsson, Mr. August Sigfrid",male,28.0,0,0,350042,7.7958,NaN,S
817,818,0,2,"Mallet, Mr. Albert",male,31.0,1,1,S.C./PARIS 2079,37.0042,NaN,C
662,663,0,1,"Colley, Mr. Edward Pomeroy",male,47.0,0,0,5727,25.5875,E58,S
430,431,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.0,0,0,110564,26.5500,C52,S

# **Part 3**
## **Exercise 3**
### 1. Columns and rows counts

In [13]:
print(f"Df has {df.shape[1]} columns, and {df.shape[0]} rows")

Df has 12 columns, and 891 rows

### 2. Column types

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

#### 2.1 Identifying which columns are numeric and which are array

In [15]:
df_types = dict(df.dtypes)
df_types_final = {"numeric": [], "text": []}
for key, value in df_types.items():
    if str(value).startswith(("int", "float")):
        df_types_final["numeric"].append(key)
    else:
        df_types_final["text"].append(key)

df_types_final

{'numeric': ['PassengerId',
  'Survived',
  'Pclass',
  'Age',
  'SibSp',
  'Parch',
  'Fare'],
 'text': ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']}

### 3. Using df.describe()

In [16]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Mean age is approximately **29.7** years old, and the maximum fare is approximately **512.33**.
### 4. Males and females counts

In [17]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### 5. Possible values of Pclass

In [18]:
pclass_values = df["Pclass"].unique()
pclass_values.sort()
print(pclass_values)

[1 2 3]

#### 5.1 How many passengers in each class

In [19]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

### 6. Using d.info()

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

Age column has **177** missing values, Cabin has **687**, and Embarked has **2**, the others are complete.
# **Part 4**
## **Exercise 4**
### 1. Displaying Name column

In [21]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### 2. Displaying Name, Sex, and age for the first 10 passengers

In [22]:
df.loc[0: 9, ["Name", "Sex", "Age"]]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

### 3. Displaying the row 100

In [23]:
df.iloc[100]

PassengerId                        101
Survived                             0
Pclass                               3
Name           Petranec, Miss. Matilda
Sex                             female
Age                               28.0
SibSp                                0
Parch                                0
Ticket                          349245
Fare                            7.8958
Cabin                              NaN
Embarked                             S
Name: 100, dtype: object

### 4. Displaying fare value of the passenger at position 50

In [24]:
df.loc[50, ["Fare"]]

Fare    39.6875
Name: 50, dtype: float64

# **Part 5**
## **Exercise 5**
### 1. Passengers older than 60

In [25]:
df[df["Age"] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

### 2. Women count in 1st class

In [26]:
df[(df["Pclass"] == 1) & (df["Sex"] == "female")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

### 3. Passengers under 10 years and survived

In [27]:
df[(df["Survived"] == 1) & (df["Age"] < 10)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,NaN,S
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S

### 4. Passengers fare above 100

In [28]:
df.loc[df["Fare"] > 100, ["Name", "Fare", "Pclass"]]

                                                  Name      Fare  Pclass
27                      Fortune, Mr. Charles Alexander  263.0000       1
31      Spencer, Mrs. William Augustus (Marie Eugenie)  146.5208       1
88                          Fortune, Miss. Mabel Helen  263.0000       1
118                           Baxter, Mr. Quigg Edmond  247.5208       1
195                               Lurette, Miss. Elise  146.5208       1
215                            Newell, Miss. Madeleine  113.2750       1
258                                   Ward, Miss. Anna  512.3292       1
268      Graham, Mrs. William Thompson (Edith Junkins)  153.4625       1
269                             Bissette, Miss. Amelia  135.6333       1
297                       Allison, Miss. Helen Loraine  151.5500       1
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208       1
305                     Allison, Master. Hudson Trevor  151.5500       1
306                            Fleming, Miss. Margaret  110.8833       1
307  Penasco y Castellana, Mrs. Victor de Satode (M...  108.9000       1
311                         Ryerson, Miss. Emily Borie  262.3750       1
318                           Wick, Miss. Mary Natalie  164.8667       1
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  134.5000       1
325                           Young, Miss. Marie Grice  135.6333       1
332                          Graham, Mr. George Edward  153.4625       1
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  133.6500       1
337                    Burns, Miss. Elizabeth Margaret  134.5000       1
341                     Fortune, Miss. Alice Elizabeth  263.0000       1
373                                Ringhini, Mr. Sante  135.6333       1
377                          Widener, Mr. Harry Elkins  211.5000       1
380                              Bidois, Miss. Rosalie  227.5250       1
390                         Carter, Mr. William Ernest  120.0000       1
393                             Newell, Miss. Marjorie  113.2750       1
435                          Carter, Miss. Lucile Polk  120.0000       1
438                                  Fortune, Mr. Mark  263.0000       1
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  151.5500       1
505         Penasco y Castellana, Mr. Victor de Satode  108.9000       1
527                                 Farthing, Mr. John  221.7792       1
537                                LeRoy, Miss. Bertha  106.4250       1
544                         Douglas, Mr. Walter Donald  106.4250       1
550                        Thayer, Mr. John Borland Jr  110.8833       1
557                                Robbins, Mr. Victor  227.5250       1
581  Thayer, Mrs. John Borland (Marian Longstreth M...  110.8833       1
609                          Shutes, Miss. Elizabeth W  153.4625       1
659                         Newell, Mr. Arthur Webster  113.2750       1
660                      Frauenthal, Dr. Henry William  133.6500       1
679                 Cardeza, Mr. Thomas Drake Martinez  512.3292       1
689                  Madill, Miss. Georgette Alexandra  211.3375       1
698                           Thayer, Mr. John Borland  110.8833       1
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  227.5250       1
708                               Cleaver, Miss. Alice  151.5500       1
716                      Endres, Miss. Caroline Louise  227.5250       1
730                      Allen, Miss. Elisabeth Walton  211.3375       1
737                             Lesurer, Mr. Gustave J  512.3292       1
742              Ryerson, Miss. Susan Parker "Suzette"  262.3750       1
763          Carter, Mrs. William Ernest (Lucile Polk)  120.0000       1
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  211.3375       1
802                Carter, Master. William Thornton II  120.0000       1
856         Wick, Mrs. George Dennick (Mary Hitchcock)  164.8667       1

# **Part 6**
## **Exercise 6**
### 1. Creating a column family

In [29]:
df["Famiy_size"] = df["SibSp"] + df["Parch"] + 1
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Famiy_size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

### 2. Sorting df by Age and displaying the 5 oldest passengers

In [30]:
df.sort_values("Age", ascending=False).head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Famiy_size
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,1
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,1
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,1
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,1

### 3. Creating df_renamed and displaying its columns

In [31]:
df_renamed = df.rename(columns={"Survived": "Survival"})
df_renamed.columns

Index(['PassengerId', 'Survival', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Famiy_size'],
      dtype='str')

### 4. Calculating the average survival rate
#### 4.1. By sex

In [32]:
df_renamed.groupby("Sex")["Survival"].mean()

Sex
female    0.742038
male      0.188908
Name: Survival, dtype: float64

#### 4.2. By class

In [33]:
df_renamed.groupby("Pclass")["Survival"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survival, dtype: float64

### 5. Computing the average fare paid by class

In [34]:
df_renamed.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

# **Part 7**
## **Exercise 7**
### 1. Overall Percentage of survivors

In [35]:
print(f"%{df["Survived"].mean() * 100 :.2f}")

%38.38

### 2. Detrmining which class has the highest survival rate

In [36]:
print(df.groupby("Pclass")["Survived"].mean().idxmax())
# Or df.groupby("Pclass")["Survived"].mean().sort_values(ascending=False).index[0]

1

### 3. Survival average for children under 12

In [37]:
print(df[df["Age"] < 12]["Survived"].mean())

0.5735294117647058

### 4. Passenger who paid the highest fare

In [38]:
df.nlargest(1, columns="Fare", keep="all")
# Or df[df["Fare"] == df["Fare"].max()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Famiy_size
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,1
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,1

### 5. Exporting survivors_1st
#### 5.1. Creating survivors_1st

In [39]:
survivors_1st = df.loc[df["Pclass"] == 1, ["Name", "Sex", "Age", "Fare"]]
survivors_1st

                                                  Name     Sex   Age     Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000
6                              McCarthy, Mr. Timothy J    male  54.0  51.8625
11                            Bonnell, Miss. Elizabeth  female  58.0  26.5500
23                        Sloper, Mr. William Thompson    male  28.0  35.5000
..                                                 ...     ...   ...      ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0  52.5542
872                           Carlsson, Mr. Frans Olof    male  33.0   5.0000
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0  83.1583
887                       Graham, Miss. Margaret Edith  female  19.0  30.0000
889                              Behr, Mr. Karl Howell    male  26.0  30.0000

[216 rows x 4 columns]

#### 5.2. Exporting survivors_1st

In [40]:
survivors_1st.to_csv("survivors_1st.csv", index=False)